import { getTranslations } from "next-intl/server"
import Image from "next/image"
import image1 from "../../images/Container (9).png"
import image6 from "../../images/image.png"
import image7 from "../../images/image copy.png"
import image8 from "../../images/image copy 2.png"
import image9 from "../../images/image copy 3.png"

import personImage from "../../images/Background (3).png"
import personImage2 from "../../images/Elena Vance (1).png"
import personImage3 from "../../images/Background (6).png"
import personImage4 from "../../images/Background (8).png"

import imageIcon from "../../images/Icon (1).png"
import imageIcon1 from "../../images/Icon (5).png"
import imageIcon2 from "../../images/Icon (6).png"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: "About Page",
    description: "Generated by create next app",
};

const AboutPage = async () => {
    const t = await getTranslations("AboutPage");
    return (
        <div className="mt-5">
            <section className="flex w-[90%] m-auto items-center justify-between">
                <div className="">
                    <span className="text-[#4EDEA3] px-4 bg-[#002113] mb-6 rounded-xl">{t("established")}</span>
                    <h1 className="text-[#000000] text-8xl mb-6 font-bold">
                        {t.rich("title", {
                            br: () => <br />
                        })}
                    </h1>
                    <p className="mb-9 w-[70%] text-[#45464D] font-semibold">
                        {t("description")}
                    </p>
                    <p className="text-[#191C1E] font-bold">{t("manifesto")}</p>
                </div>
                <Image className="w-169 h-169" src={image1} alt="" />
            </section>
            <section className="bg-[#F2F4F6] mb-24 py-20 px-20">
                <div className="mb-16">
                    <h1 className="text-[#000000] font-bold mb-6 text-2xl">{t("philosophy.title")}</h1>
                    <p className="text-[#45464D] font-semibold mb-20">
                        {t("philosophy.description")}
                    </p>
                </div>
                <div className="grid grid-cols-3 gap-8">
                    <div className="bg-white p-10 rounded-xl">
                        <Image className="mb-4" src={imageIcon} alt="" />
                        <h1 className="mb-4 text-[#191C1E] font-bold text-2xl">{t("philosophy.precision.title")}</h1>
                        <p className="text-[#45464D] font-semibold">
                            {t("philosophy.precision.description")}
                        </p>
                    </div>
                    <div className="bg-white p-10 rounded-xl">
                        <Image className="mb-4" src={imageIcon1} alt="" />
                        <h1 className="mb-4 text-[#191C1E] font-bold text-2xl">{t("philosophy.soul.title")}</h1>
                        <p className="text-[#45464D] font-semibold">
                            {t("philosophy.soul.description")}
                        </p>
                    </div>
                    <div className="bg-white p-10 rounded-xl">
                        <Image className="mb-4" src={imageIcon2} alt="" />
                        <h1 className="mb-4 text-[#191C1E] font-bold text-2xl">{t("philosophy.legacy.title")}</h1>
                        <p className="text-[#45464D] font-semibold">
                            {t("philosophy.legacy.description")}
                        </p>
                    </div>
                </div>
            </section >
            <section className="">
                <div className="text-center">
                    <h1 className="text-[#000000] font-bold mb-4 text-4xl">{t("team.title")}</h1>
                    <p className="text-[#45464D] font-semibold">
                        {t("team.description")}
                    </p>
                </div>
                <div className="grid grid-cols-4 gap-12 my-20 w-[90%] m-auto">
                    <div className="">
                        <Image className="mb-3" src={personImage} alt="" />
                        <h3 className="text-[#191C1E] font-bold text-lg mb-1.5">{t("team.marcus.name")}</h3>
                        <p className="text-[#45464D] font-bold text-xs">{t("team.marcus.role")}</p>
                    </div>
                    <div className="">
                        <Image className="mb-3" src={personImage2} alt="" />
                        <h3 className="text-[#191C1E] font-bold text-lg mb-1.5">{t("team.elena.name")}</h3>
                        <p className="text-[#45464D] font-bold text-xs">{t("team.elena.role")}</p>
                    </div>
                    <div className="">
                        <Image className="mb-3" src={personImage3} alt="" />
                        <h3 className="text-[#191C1E] font-bold text-lg mb-1.5">{t("team.julian.name")}</h3>
                        <p className="text-[#45464D] font-bold text-xs">{t("team.julian.role")}</p>
                    </div>
                    <div className="">
                        <Image className="mb-3" src={personImage4} alt="" />
                        <h3 className="text-[#191C1E] font-bold text-lg mb-1.5">{t("team.sarah.name")}</h3>
                        <p className="text-[#45464D] font-bold text-xs">{t("team.sarah.role")}</p>
                    </div>
                </div>
            </section>
            <section className="bg-[#f6f6f6] py-10">
                <div className="w-[90%] m-auto">
                    <div className="text-start mb-16">
                        <h1 className="text-[#000000] font-bold mb-4 text-4xl">{t("studio.title")}</h1>
                        <p className="text-[#45464D] font-semibold">{t("studio.description")}</p>
                    </div>
                    <div className="flex items-center justify-between gap-10">
                        <Image className="rounded-2xl w-150 h-150" src={image6} alt="" />
                        <div>
                            <Image className="mb-5 w-182 h-70 rounded-2xl" src={image7} alt="" />
                            <div className="flex items-center gap-4">
                                <Image className="w-150 h-70 rounded-2xl" src={image8} alt="" />
                                <Image className="w-150 h-70 rounded-2xl" src={image9} alt="" />
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section className="bg-[#fff8f8] py-10">
                <div className="w-[90%] m-auto">
                    <div className="text-center mb-16">
                        <h1 className="text-[#000000] font-bold mb-4 text-4xl">
                            {t.rich("bottomCta.title", {
                                br: () => <br />
                            })}
                        </h1>
                        <p className="text-[#45464D] font-semibold mb-8">
                            {t("bottomCta.description")}
                        </p>
                        <div className="flex items-center gap-5 justify-center">
                            <button className="text-white bg-[#000000] py-4 px-10 rounded-xl">{t("bottomCta.partner")}</button>
                            <button className="text-[#57657B] bg-[#D5E3FD] py-4 px-10 rounded-xl">{t("bottomCta.portfolio")}</button>
                        </div>
                    </div>

                </div>
            </section>
        </div >
    )
}

export default AboutPage
