import {
  Mail,
  Phone,
  MapPin,
  AtSign,
  Globe,
  Play,
  Briefcase,
} from "lucide-react";

import image1 from "../../images/Section - Google Maps Placeholder.png"
import Image from "next/image";
import { Metadata } from "next";
import { getTranslations } from "next-intl/server";

export const metadata: Metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};

const ContactPage = async () => {
  const t = await getTranslations("ContactPage");
  return (
    <div>

      <div className="min-h-screen bg-gray-100 flex items-center justify-center p-6">
        <div className="max-w-6xl w-full bg-white rounded-2xl shadow-lg grid md:grid-cols-2 gap-0 overflow-hidden">
          <div className="p-10">
            <h2 className="text-2xl font-bold mb-6">{t("form.title")}</h2>
            <div className="grid grid-cols-2 gap-4 mb-4">
              <input
                type="text"
                placeholder={t("form.name")}
                className="bg-gray-100 p-3 rounded-md outline-none"
              />
              <input
                type="email"
                placeholder={t("form.email")}
                className="bg-gray-100 p-3 rounded-md outline-none"
              />
            </div>

            <select className="w-full bg-gray-100 p-3 rounded-md mb-4 outline-none">
              <option>{t("form.inquiry")}</option>
              <option>{t("form.support")}</option>
              <option>{t("form.business")}</option>
            </select>

            <textarea
              placeholder={t("form.message")}
              className="w-full bg-gray-100 p-3 rounded-md h-32 outline-none mb-6"
            ></textarea>

            <button className="w-full bg-black text-white py-3 rounded-lg font-semibold hover:opacity-90 transition">
              {t("form.submit")}
            </button>
          </div>

          <div className="bg-gray-50 p-10">
            <h2 className="text-2xl font-bold mb-4">{t("info.title")}</h2>
            <p className="text-gray-600 mb-8">
              {t("info.description")}
            </p>

            <div className="space-y-6 mb-10">
              <div className="flex items-start gap-4">
                <Mail className="text-gray-600" />
                <div>
                  <p className="text-sm text-gray-500">{t("info.email")}</p>
                  <p className="font-medium">hello@arch-editorial.com</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <Phone className="text-gray-600" />
                <div>
                  <p className="text-sm text-gray-500">{t("info.phone")}</p>
                  <p className="font-medium">+1 (555) 012-3456</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <MapPin className="text-gray-600" />
                <div>
                  <p className="text-sm text-gray-500">{t("info.address")}</p>
                  <p className="font-medium">
                    {t.rich("info.addressValue", {
                      br: () => <br />
                    })}
                  </p>
                </div>
              </div>
            </div>

            <div>
              <p className="text-sm text-gray-500 mb-4">{t("info.social")}</p>
              <div className="grid grid-cols-4 gap-4">
                {[AtSign, Globe, Play, Briefcase].map((Icon, i) => (
                  <div
                    key={i}
                    className="bg-gray-200 h-16 rounded-xl flex items-center justify-center hover:bg-gray-300 cursor-pointer transition"
                  >
                    <Icon className="text-gray-700" />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
      <Image className="w-full" src={image1} alt="" />
      <div className="w-full bg-[#0f1b2d] py-16 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-6">
            {t("bottomCta.title")}
          </h1>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="bg-[#6EE7B7] text-black px-6 py-3 rounded-md font-semibold hover:opacity-90 transition">
              {t("bottomCta.consultation")}
            </button>
            <button className="border border-gray-400 text-white px-6 py-3 rounded-md font-semibold hover:bg-white hover:text-black transition">
              {t("bottomCta.portfolio")}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContactPage;