import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import image1 from "../images/Group 79.png"

import Image from "next/image";
import telegramicon from "../images/image 294.png"
import instagramicon from "../images/image 295.png"
import { NextIntlClientProvider } from "next-intl";
import "../globals.css"
import { getTranslations, getMessages } from "next-intl/server";
import LocaleSwitcher from "@/src/components/LocaleSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Taxi Sluqba",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params;
  const t = await getTranslations();
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full w-full">
        <NextIntlClientProvider messages={messages} locale={locale}>
          <header className="flex shadow-2xl items-center justify-between p-3 backdrop-blur-md bg-white/10 z-50">
            <Image src={image1} alt="" />
            <div className="flex items-center">
              <Link href={`/${locale}`}>
                <p className="font-bold hover:text-amber-600">{t("header.h1")}</p>
              </Link>
              <p className="font-bold hover:text-amber-600 ml-4">{t("header.h2")}</p>
              <Link href={`/${locale}/faq`}>
                <p className="font-bold hover:text-amber-600 ml-4">{t("header.h3")}</p>
              </Link>
              <Link href={`/${locale}/delivery`}>
                <p className="font-bold hover:text-amber-600 ml-4">{t("header.h4")}</p>
              </Link>
              <p className="font-bold hover:text-amber-600 ml-4">{t("header.h5")}</p>
            </div>
            <div className="flex items-center">
              <p className="font-bold text-2xl">{t("header.h6")}</p>
              <LocaleSwitcher />
            </div>
          </header>

          <main className="flex flex-col">
            {children}
          </main>

          <footer className="bg-[#1E1E1E] py-15 w-full mt-auto text-white">
            <div className="flex items-center justify-between w-[85%] m-auto">
              <div className="">
                <div className="flex mb-15 items-center gap-5">
                  <p className="font-bold">{t("footer.f1")}</p>
                  <p className="font-bold">{t("footer.f2")}</p>
                  <p className="font-bold">{t("footer.f3")}</p>
                  <p className="font-bold">{t("footer.f4")}</p>
                  <p className="font-bold">{t("footer.f5")}</p>
                </div>
                <div className="flex items-center gap-5">
                  <p className="font-bold text-gray-500">{t("footer.f6")}</p>
                  <div className="flex items-center">
                    <Image src={telegramicon} alt="" />
                    <Image src={instagramicon} alt="" />
                  </div>
                </div>
              </div>
              <div className="">
                <Image className="mb-10 ml-28" src={image1} alt="" />
                <div className="flex items-center gap-4">
                  <p className="font-bold text-gray-500">{t("footer.f7")}</p>
                  <p className="font-bold text-gray-500">{t("footer.f8")}</p>
                </div>
              </div>
            </div>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

