import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import image1 from "../images/Container.png"
import image2 from "../images/Container (1).png"
import Image from "next/image";

import "../globals.css"
import Link from "next/link";
import { getTranslations} from "next-intl/server";
import { routing } from "@/src/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

import ChangeLangSelect from "../components/changeLangSelect";
import { hasLocale, NextIntlClientProvider } from "next-intl";

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const t = await getTranslations("Layout");

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full w-full">
        <NextIntlClientProvider locale={locale} messages={(await import(`@/messages/${locale}.json`)).default}>

          <header className="flex shadow-2xl sticky top-0 items-center px-10 xl:px-24 justify-between p-4 backdrop-blur-xl bg-white/80 border-b border-white/20 z-50">
            <Image src={image1} alt="Logo" className="w-48" />
            <div className="hidden md:flex items-center gap-10">
              <Link href={`/${locale}`}>
                <p className="text-[#64748B] font-bold text-sm tracking-widest uppercase hover:text-[#0F172A] transition-colors">{t("home")}</p>
              </Link>
              <p className="text-[#64748B] font-bold text-sm tracking-widest uppercase hover:text-[#0F172A] transition-colors cursor-pointer">{t("services")}</p>
              <Link href={`/${locale}/about`}>
                <p className="text-[#64748B] font-bold text-sm tracking-widest uppercase hover:text-[#0F172A] transition-colors">{t("about")}</p>
              </Link>
              <Link href={`/${locale}/contact`}>
                <p className="text-[#64748B] font-bold text-sm tracking-widest uppercase hover:text-[#0F172A] transition-colors">{t("contact")}</p>
              </Link>
            </div>
            <div className="flex items-center gap-6">
              <ChangeLangSelect />
              <button className="bg-[#000000] text-white py-3 px-8 rounded-full font-bold text-xs tracking-[0.2em] hover:bg-gray-800 transition-all shadow-xl hover:scale-105 active:scale-95">
                {t("getStarted")}
              </button>
            </div>
          </header>

          <main className="flex flex-col">
            {children}
          </main>

          <footer className="mt-20 bg-[#F9FAFB] py-20">
            <div className=" flex w-[90%] m-auto justify-between items-start pb-10">
              <div className="max-w-md">
                <Image className="mb-6" src={image1} alt="" />
                <p className="text-[#45464D] font-medium leading-relaxed uppercase text-sm tracking-wide">
                  {t("description")}
                </p>
              </div>
              <div>
                <h2 className="text-[#191C1E] font-bold text-lg mb-6">{t("explore.title")}</h2>
                <p className="text-[#64748B] font-semibold text-xs mb-4 cursor-pointer hover:text-black">{t("explore.sitemap")}</p>
                <p className="text-[#64748B] font-semibold text-xs mb-4 cursor-pointer hover:text-black">{t("explore.newsletter")}</p>
                <p className="text-[#64748B] font-semibold text-xs mb-4 cursor-pointer hover:text-black">{t("explore.insights")}</p>
                <p className="text-[#64748B] font-semibold text-xs cursor-pointer hover:text-black">{t("explore.pressKit")}</p>
              </div>
              <div>
                <h2 className="text-[#191C1E] font-bold text-lg mb-6">{t("legal.title")}</h2>
                <p className="text-[#64748B] font-semibold text-xs mb-4 cursor-pointer hover:text-black">{t("legal.privacy")}</p>
                <p className="text-[#64748B] font-semibold text-xs mb-4 cursor-pointer hover:text-black">{t("legal.terms")}</p>
                <p className="text-[#64748B] font-semibold text-xs cursor-pointer hover:text-black">{t("legal.cookie")}</p>
              </div>
            </div>
            <hr className="border border-gray-200 w-[90%] m-auto" />
            <div className="w-[90%] m-auto mt-8 flex items-center justify-between">
              <p className="text-[#64748B] text-sm font-medium">{t("copyright")}</p>
              <Image className="opacity-50" src={image2} alt="" />
            </div>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html >
  );
}

